<!DOCTYPE html>  
<html lang="ja">  
<head>  
    <meta charset="utf-8">  
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?php echo $this->headLink()->appendStylesheet('/css/main.css') ?>
    <?php echo $this->headTitle(); ?>
</head>  
<body>  

<header>
    SHIORI FACTORY
</header>


<nav>
    <a href="/index/">Home</a>
    <a href="/edit/">NEW</a>
    <a href="/show/">show</a>
</nav>

<section> 
    <?php echo $this->layout()->content ?> 
</section>

<div style="clear:both"></div>

</body>  
</html> 
