<h1>スケジュール一覧</h1>

<article>
<table>
    <tr>
    <th>title</th>
    <th>thema</th>
    <th>start_date</th>
    <th>end_date</th>
    <th>edit</th>
    </tr>
    <?php foreach($this->shioriList as $list): ?>
        <tr>
        <td><?php echo $list['title']; ?></td>
        <td><?php echo $list['thema']; ?></td>
        <td class="center">
            <?php echo str_replace('-', '/', $list['start_date']); ?>
        </td>
        <td class="center">
            <?php echo str_replace('-', '/', $list['end_date']); ?>
        </td>
        <td class="center">
            <a href="/show/detail?id=<?php echo $list['id']; ?>">詳細</a>
            <a href="/edit/?id=<?php echo $list['id']; ?>">編集</a>
            <a href="/edit/delete?id=<?php echo $list['id']; ?>">削除</a>
        </td>
        </tr>
    <?php endforeach; ?>
</article>
